function [value] = average_plaquette_su3(config,Nx,Nt)

value=0;

for nx=1:(Nx-1)
for ny=1:(Nx-1)
for nz=1:(Nx-1)
for nt=1:(Nt-1)
    
    value=value+real(trace(build_su3(config(1,nx,ny,nz,nt,1,:))* ...
        build_su3(config(1,nx+1,ny,nz,nt,2,:))* ...
        ctranspose(build_su3(config(1,nx,ny+1,nz,nt,1,:)))* ...
        ctranspose(build_su3(config(1,nx,ny,nz,nt,2,:)))));
    
    value=value+real(trace(build_su3(config(1,nx,ny,nz,nt,1,:))* ...
        build_su3(config(1,nx+1,ny,nz,nt,3,:))* ...
        ctranspose(build_su3(config(1,nx,ny,nz+1,nt,1,:)))* ...
        ctranspose(build_su3(config(1,nx,ny,nz,nt,3,:)))));
    
    value=value+real(trace(build_su3(config(1,nx,ny,nz,nt,1,:))* ...
        build_su3(config(1,nx+1,ny,nz,nt,4,:))* ...
        ctranspose(build_su3(config(1,nx,ny,nz,nt+1,1,:)))* ...
        ctranspose(build_su3(config(1,nx,ny,nz,nt,4,:)))));
    
    value=value+real(trace(build_su3(config(1,nx,ny,nz,nt,2,:))* ...
        build_su3(config(1,nx,ny+1,nz,nt,3,:))* ...
        ctranspose(build_su3(config(1,nx,ny,nz+1,nt,2,:)))* ...
        ctranspose(build_su3(config(1,nx,ny,nz,nt,3,:)))));
    
    value=value+real(trace(build_su3(config(1,nx,ny,nz,nt,2,:))* ...
        build_su3(config(1,nx,ny+1,nz,nt,4,:))* ...
        ctranspose(build_su3(config(1,nx,ny,nz,nt+1,2,:)))* ...
        ctranspose(build_su3(config(1,nx,ny,nz,nt,4,:)))));
    
    value=value+real(trace(build_su3(config(1,nx,ny,nz,nt,3,:))* ...
        build_su3(config(1,nx,ny,nz+1,nt,4,:))* ...
        ctranspose(build_su3(config(1,nx,ny,nz,nt+1,3,:)))* ...
        ctranspose(build_su3(config(1,nx,ny,nz,nt,4,:)))));
    
end
end
end
end

% 6 is the number of plaquettes per lattice point, and 3 is the number of
% color charges
value=value/(Nx-1)^3/(Nt-1)/6/3;

end

